### ISSUE TITLE
Missing wheels for Python 3.8

### ISSUE THREAD

**Issue by alexhenrie** [althonos/nanoset.py#1]
Ever since Arch Linux updated to Python 3.8, I have been unable to install nanoset. No wheels for Python 3.8 are available, so pip tries to compile it from source, but fails because Arch's rust package is on the latest stable release and Arch's rust-nightly package is broken. Could you please consider publishing Python 3.8 wheels from now on?

**Comment by althonos** [comment]
Hi @alexhenrie,
I was waiting for the `manylinux` Docker image I use to build the wheels to support Python 3.8, which it only started to do 10 days ago. I just released a new version of the library, and I will support wheels for Python 3.8 from now on!

(btw, from an Arch user to another, the proper way to install Rust on Arch is with [`rustup`](https://www.archlinux.org/packages/community/x86_64/rustup/) to always have access to the most recent compilers, but unless you use Rust a lot you probably don't care :wink: )

**Comment by alexhenrie** [comment]
Thank you!
