### ISSUE TITLE
Nanoset with Python 3.8 on MacOS

### ISSUE THREAD

**Issue by mpreusse** [althonos/nanoset.py#3]
There is no pre-compiled version available for Python 3.8 on MacOS.

Would be helpful to note this dependency issue. To install with Python 3.8 on MacOS you need the rust toolchain.

**Comment by althonos** [comment]
Hi @mpreusse ,

I updated the CI/CD pipeline and now Mac OSX has a wheel for Python 3.5 and 3.8 as well. The requirement for a Rust toolchain is listed in the *Installing* section of the README if I'm not wrong.

Cheers!
